# -*- coding: utf-8 -*-
"""detecting_outliers_with_IQR.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13W2J0l0FSFT83tK1LCL1wf-uLpW0kGaU
"""

# input dataset
data_input = input("Your dataset: ")
data_list = data_input.split(',')

dataset = [int(data) for data in data_list]

# calculate min value
min_value = min(dataset)

# calculate quartiles
import numpy as np

data = dataset

quartiles = np.percentile(data, [25, 50, 75])

q1 = quartiles[0]
median = quartiles[1]
q3 = quartiles[2]

# calculate max value
max_value = max(dataset)


# calculate mean
mean_value = sum(dataset)/(len(dataset))


# calculate IQR
iqr_value = q3 - q1


# calculate the lower limit outliers
lower_limit_value = q1 - (iqr_value * 1.5)


# calculate the upper limit outliers
upper_limit_value = q3 + (iqr_value * 1.5)


import pandas as pd

from tabulate import tabulate

results = [
    ["Min", min_value],
    ["Q1", q1],
    ["Median", median],
    ["Q3", q3],
    ["Max", max_value],
    ["Mean", mean_value],
    ["IQR", iqr_value],
    ["Lower Limit", lower_limit_value],
    ["Upper Limit", upper_limit_value]
]

results_df = pd.DataFrame(results, columns=["Statistic", "Value"])

results_df = results_df.set_index('Statistic')

tabular_results = tabulate(results_df, headers='keys', tablefmt='fancy_grid')

print(tabular_results)

from tabulate import tabulate

results = [
    ["Min", min_value],
    ["Q1", q1],
    ["Median", median],
    ["Q3", q3],
    ["Max", max_value],
    ["Mean", mean_value],
    ["IQR", iqr_value],
    ["Lower Limit", lower_limit_value],
    ["Upper Limit", upper_limit_value]
]

# Convert results to a tabular format
tabular_results = tabulate(results, headers=["Statistic", "Value"], tablefmt="fancy_grid")

print(tabular_results)

